MOCK_TOOL_RESPONSES = [
    # PlanningAgent: create plan
    r"""ChatCompletion(id='replay-BCQrdZ1d25KWxkoO5AJ9TfypIA9mE', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_DDkLV5q8GUjfpSq1KtakwnCj', function=Function(arguments='{"command":"create","plan_id":"plan_10005632","title":"Save Organizational Structure Reporting to MarkL","steps":["Identify the organizational structure and list everyone reporting to MarkL.","Organize the information in a structured format suitable for a text file.","Save the organized information into a text file."]}', name='planning'), type='function')]))], created=1742302901, model='gpt-4o-2024-08-06', object='chat.completion', service_tier='default', system_fingerprint='fp_90d33c15d4')""",
    # MaestroAgent: data_lookup
    r"""ChatCompletion(id='replay-BCRt4HEN6yLGrNCrjnl9qBzspuaID', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_YSmAUS7HCcgprM6AmS2QKsYj', function=Function(arguments='{"source":"organizational_database","query":"everyone reporting to MarkL"}', name='data_lookup'), type='function')]))], created=1742306834, model='gpt-4o-2024-08-06', object='chat.completion', service_tier='default', system_fingerprint='fp_f9f4fb6dbf')""",
    # PlanningAgent: complete step 0
    r"""ChatCompletion(id='replay-BCS1XXKcDb5MTtqvL8d0m5tauJKsb', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_Y6UxWLoKSkMn60rRUe33PaAr', function=Function(arguments='{"command":"mark_step","plan_id":"plan_10005632","step_index":0,"step_status":"completed","step_notes":"Identified the organizational structure and listed everyone reporting to MarkL."}', name='planning'), type='function')]))], created=1742307359, model='gpt-4o-2024-08-06', object='chat.completion', service_tier='default', system_fingerprint='fp_90d33c15d4')""",
    # MaestroAgent: create information structure
    r"""ChatCompletion(id='replay-BCS93lB66hME7CkjTk3r0HFnEaJ0B', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content="The next step is to organize the information in a structured format suitable for a text file. Here's how the information can be structured:\n\n```\nOrganizational Structure Reporting to Mark Little:\n\n1. Mark Proctor\n   - Kris Verlaenen\n\n2. David Gutierrez\n   - Ricardo Zanini\n   - Francisco Javier Tirado Sarti\n\n3. Marek Novotny\n   - Mario Fusco\n```\n\nThis format clearly shows the hierarchy and the reporting lines under Mark Little. \n\nI will now proceed to mark this step as completed.", refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[]))], created=1742307825, model='gpt-4o-2024-08-06', object='chat.completion', service_tier='default', system_fingerprint='fp_f9f4fb6dbf')""",
    # PlanningAgent: complete step 1
    r"""ChatCompletion(id='replay-BCSDlz4Q1vR4nRb3CthOp5em5vNv9', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_TioVg58h1RKKHTfa3z3UGqTg', function=Function(arguments='{"command":"mark_step","plan_id":"plan_10005632","step_index":1,"step_status":"completed","step_notes":"Organized the information in a structured format suitable for a text file."}', name='planning'), type='function')]))], created=1742308117, model='gpt-4o-2024-08-06', object='chat.completion', service_tier='default', system_fingerprint='fp_90d33c15d4')""",
    # MaestroAgent: create file
    r"""ChatCompletion(id='replay-BCSEwGOwdyDmoaKfG06dc3jp60XpY', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_aG57W18yeIzzVpblhNojDr6D', function=Function(arguments='{"content":"Organizational Structure Reporting to Mark Little:\\n\\n1. Mark Proctor\\n   - Kris Verlaenen\\n\\n2. David Gutierrez\\n   - Ricardo Zanini\\n   - Francisco Javier Tirado Sarti\\n\\n3. Marek Novotny\\n   - Mario Fusco","file_path":"organizational_structure_markl.txt"}', name='file_saver'), type='function')]))], created=1742308190, model='gpt-4o-2024-08-06', object='chat.completion', service_tier='default', system_fingerprint='fp_f9f4fb6dbf')""",
    # PlanningAgent: complete step 2
    r"""ChatCompletion(id='replay-BCSHqOsV7BmPx8t7e7SJIZKV7aTsT', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_NFjJnG2ZvzMz7QoI1cek0mHF', function=Function(arguments='{"command":"mark_step","plan_id":"plan_10005632","step_index":2,"step_status":"completed","step_notes":"Saved the organized information into a text file named \'organizational_structure_markl.txt\'."}', name='planning'), type='function')]))], created=1742308370, model='gpt-4o-2024-08-06', object='chat.completion', service_tier='default', system_fingerprint='fp_90d33c15d4')"""
]

